#pragma once

#define GAME_LOOP_FPS 60.0
#define GAME_LOOP_PERIOD_s 1 / GAME_LOOP_FPS
#define GAME_LOOP_PERIOD_ms 1000 / GAME_LOOP_FPS

#define DEFAULT_DAS 95; 
#define DEFAULT_ARR INT32_MAX; 
#define DEFAULT_ARP 1000.0 / ARR; 
#define DEFAULT_SDF -1; 
